### PR TITLE
cove: Add closed codelist validation 

### PR DESCRIPTION
**Pull request by Bjwebb**

### CODE REVIEW

**Comment by Bjwebb** [comment]
Currently this is copy/pasted directly from cove-ocds, so is styled wrongly.

Screenshot from 2022-11-23 17-49-51

I'm thinking of changing the above section to "This data does not use the 360Giving Data Standard structure correctly", and the codelist section can be "This data does not use the 360Giving Data Standard codelists correctly". @michaelwood What do you think?

**Comment by mariongalley** [comment]
@Bjwebb The new normative guidance on codelists says: ""Because the codelists currently available in the Standard are closed, only codes from the codelists may be used. Any other code included in the data will result in invalid data. "

The current subheadings under "This data does not use the 360Giving Standard" are "Missing Fields", "Incorrect Formats" and "Other", so I think calling this "Codelist Errors" (or perhaps "Invalid Codelist codes") is more in keeping with that brevity.

The current descriptions are e.g. "Some or all of your entries were missing fields which are required by the 360Giving Standard." and "Some or all of your entries have incorrectly formatted data." so I think "Some or all of your entries do not use the 360Giving Data Standard codelists correctly." works. Alternatively "Some or all of your entries do not use valid codes from the 360Giving Data Standard codelists."

**Comment by KDuerden** [comment]
That looks great, I'm happy with this for go live next week thank you.

I have a question about the existing codelist error messages - which trigger for currency & country code. Does the above change affect those too, or will we have two types of codelist errors, one for enum and one for csv hosted codelists?

image

Depending on the answer, longer term it would be good to give users a consistent style of error message whichever type of closed codelist and eg retain / incorporate the link to further info on errors from the currently live message.

**Comment by Bjwebb** [comment]
> I have a question about the existing codelist error messages - which trigger for currency & country code. Does the above change affect those too, or will we have two types of codelist errors, one for enum and one for csv hosted codelists?

As things currently stand, we'll have two types of errors.

> Depending on the answer, longer term it would be good to give users a consistent style of error message whichever type of closed codelist and eg retain / incorporate the link to further info on errors from the currently live message.

Agreed.

My preferred way to do this would be to create codelist csvs in the schema repo for the existing closed codelists. If we wish to keep the enums, we could arrange for these to be generated from the codelist csv files by a script.

I already have a script to create the csvs from the current enums, so that could be done tomorrow if we wanted to have the extra csvs for the upcoming release. (Sorry, meant to reply to this sooner, but it got lost on my todo list).

**Comment by Bjwebb** [comment]
I made a PR for csvs for the existing codelists: https://github.com/ThreeSixtyGiving/standard/pull/343

**Pull request merged**
