### PR TITLE
Add new additional tests

### PR DESCRIPTION
**Pull request by Bjwebb**

### CODE REVIEW

**Comment by Bjwebb** [comment]
Here's some screenshots of what this looks like:

Screenshot from 2023-02-08 17-53-38
Screenshot from 2023-02-08 17-53-54
Screenshot from 2023-02-08 17-54-15

I've written the text myself, happy to make any changes.

@KDuerden @mariongalley

**Comment by michaelwood** [comment]
I think s/Recipient Ind/Recipient Individual/g if you haven't already (just looking at the screenshot)

**Comment by mariongalley** [comment]
Thanks Ben - I'll take this away and return with some alternate wording. Most people won't really interface with the ToIndividualDetails object and will only have awareness of the specific codelists within it, so we'll make the warnings about Grant Purpose & Reason to be more user-friendly. We also want the warnings about DEI and postcodes to be very strong, i.e. it's essentially forbidden in every way except through hard validation.

**Comment by mariongalley** [comment]
@Bjwebb Is the warning about Beneficiary location restricted to grants that have individual recipients or all grants? The warning looks fairly generic, but ideally we'd only like to issue this warning for grants to individuals, as there's no real objection to orgs having beneficiary location postcodes.

**Comment by KDuerden** [comment]
We have had discussions as part of our standard work on location about whether we should be discouraging the inclusion of postcodes in the location geocode fields, because having a mixture of ONS codes and postcodes makes the data tricker to use. We have considered adding specific postcode field to the location definition, to give current publishers including postcodes in the geocode field somewhere to put their data. However we've held off doing anything about this for the time being.

I think for the immediate use case, this test should only be triggered when the recipient is declared using the individuals fields. However if we do want to move forward with discouraging postcodes in the location geocode field, could we revisit this in future - and set up a similar test but with different wording for grants with a recipient org?

**Comment by Bjwebb** [comment]
Here are some new screenshots with the updated copy:
Screenshot from 2023-02-20 21-50-03
Screenshot from 2023-02-20 21-51-19
Screenshot from 2023-02-20 21-51-52

**Comment by mariongalley** [comment]
Thanks @Bjwebb - I'm sorry to have kept you waiting, I think this is fine to go live as we can always amend the copy later

**Comment by Bjwebb** [comment]
> I think s/Recipient Ind/Recipient Individual/g if you haven't already (just looking at the screenshot)

I've kept this as is, as it's the title from the standard. I've put it in a highlight block though to make this more clear.

**Review by michaelwood — DISMISSED** [review]
lgtm :)

**Review by michaelwood — APPROVED** [review]

**Comment by Bjwebb** [comment]
> @Bjwebb Got some feedback to change the word "analyse" to "use data on" - I've updated the Google doc, is that OK?

Thanks, I've made that change.

This is now deployed to https://dataquality.threesixtygiving.org/

**Pull request merged**
