### PR TITLE
Grants to individuals summary count

### PR DESCRIPTION
**Pull request by michaelwood**

### CODE REVIEW

**Comment by michaelwood** [comment]
This change adds code to count recipient individuals and changes the copy to reflect there being two types of recipients.

The visible changes are on the ' Summary: Your data at a glance' section.

"There are 4 grants to 2 recipient organisations and 0 to recipient individuals."

image


The non-plural version outputs the copy:

"There are 4 grants to 2 recipient organisations and 1 to a recipient individual."

In the Advanced view the heading "Recipients" is changed to "Recipient Organisations" and a table entry is added for individuals count (0 in this example).

image

**Comment by michaelwood** [comment]
Assigned @KDuerden / @mariongalley for copy review. Thanks.

**Review by mariongalley — APPROVED** [review]
I'm happy with the proposed layout and copy, thanks Michael

**Comment by KDuerden** [comment]
It looks great thank you. Also today I learned about Advanced view. I have literally never seen that before!

**Review by KDuerden — APPROVED** [review]
Happy to approve, thank you.

**Comment by michaelwood** [comment]
Thanks over to @Bjwebb for code review.

**Review by Bjwebb — APPROVED** [review]
Ideally we'd have a test of a non-zero recipient individual count also.

**Pull request merged**
